<?php
echo "<html>\n";
echo "   <head>\n";
echo "   <title>Easy Buy</title>\n";
echo "   <link rel=\"stylesheet\"  href=\"style2.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\n";
echo "   <link rel=\"styplesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
echo "   <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" ></script>\n";
echo "script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" ></script>\n";
echo "script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" ></script>\n";
echo "</head>\n";
echo "   <body>\n";
echo "       <!-----NavigationBar---->\n";
echo "   <section id=\"nav-bar\">\n";
echo "           <nav class=\"navbar navbar-expand-lg navbar-light\">\n";
echo "                   <a class=\"navbar-brand\" href=\"#\"><img src=\"sell.jpg\"></a>\n";
echo "                   <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
echo "                     <span class=\"navbar-toggler-icon\"></span>\n";
echo "                   </button>\n";
echo "                   <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n";
echo "                     <ul class=\"navbar-nav ml-auto\">\n";
echo "                       <li class=\"nav-item active\">\n";
echo "                         <a class=\"nav-link\" href=\"#\">Home</a>\n";
echo "                       </li>\n";
echo "                       <li class=\"nav-item\">\n";
echo "                         <a class=\"nav-link\" href=\"#\">Sign Up</a>\n";
echo "                       </li>\n";
echo "                       <li class=\"nav-item\">\n";
echo "                         <a class=\"nav-link\" href=\"#\">Login</a>\n";
echo "                       </li>\n";
echo "                       <li class=\"nav-item\">\n";
echo "                         <a class=\"nav-link\" href=\"#\">List</a>\n";
echo "                       </li>\n";
echo "                       <li class=\"nav-item\">\n";
echo "                               <a class=\"nav-link\" href=\"#\">Contact</a>\n";
echo "                             </li>\n";
echo "                     </ul>\n";
echo "                   </div>\n";
echo "                 </nav>\n";
echo "/section>\n";
echo "!------------Slider----------------->\n";
echo "div id=\"slider\">\n";
echo "       <div id=\"headerSlider\" class=\"carousel slide\" data-ride=\"carousel\">\n";
echo "               <ol class=\"carousel-indicators\">\n";
echo "                 <li data-target=\"#headerSlider\" data-slide-to=\"0\" class=\"active\"></li>\n";
echo "                 <li data-target=\"#headerSlider\" data-slide-to=\"1\"></li>\n";
echo "                 <li data-target=\"#headerSlider\" data-slide-to=\"2\"></li>\n";
echo "               </ol>\n";
echo "               <div class=\"carousel-inner\">\n";
echo "                 <div class=\"carousel-item active\">\n";
echo "                   <img src=\"buy1.jpg\" class=\"d-block w-100\" >\n";
echo "                 </div>\n";
echo "                 <div class=\"carousel-item\">\n";
echo "                   <img src=\"buy2.jpg\" class=\"d-block w-100\" >\n";
echo "                 </div>\n";
echo "                 <div class=\"carousel-item\">\n";
echo "                   <img src=\"buy3.jpg\" class=\"d-block w-100\" >\n";
echo "                 </div>\n";
echo "               </div>\n";
echo "               <a class=\"carousel-control-prev\" href=\"#headerSlider\" role=\"button\" data-slide=\"prev\">\n";
echo "                 <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n";
echo "                 <span class=\"sr-only\">Previous</span>\n";
echo "               </a>\n";
echo "               <a class=\"carousel-control-next\" href=\"#headerSlider\" role=\"button\" data-slide=\"next\">\n";
echo "                 <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n";
echo "                 <span class=\"sr-only\">Next</span>\n";
echo "               </a>\n";
echo "             </div>\n";
echo "/div>\n";
echo "/body>\n";
echo "/html>\n";
?>